server:
  port: 8081
spring:
  profiles:
    active: home
#    active: company
  application:
    name: product_test
dubbo:
  application:
    version: 1.0.0
    name: product
  protocol:
    name: dubbo
    port: 20880
  monitor:
    protocol: registry
  consumer:
    check: false
  scan:
    base-packages: com.lqq.impl