server:
  port: 8085
spring:
  profiles:
    active: company
  application:
    #spring项目名
    name: userservice_test
dubbo:
  application:
    version: 1.0.0
    name: userservice
  protocol:
    name: dubbo
    port: 20882
  monitor:
    protocol: registry
  #扫描注解包通过该设置将服务注册到zookeeper
  scan:
    base-packages: com.lqq.impl
